### ISSUE TITLE
link ga href="" ni to'g'rilash kerak ekan

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [FarrukhMahkamov/Pizza#1]
![Screenshot_4](https://user-images.githubusercontent.com/77617034/116690044-43c2d380-a9d2-11eb-9431-a36f83c294c4.png)
shuni href="tel:0-800-33-08-98" qilib qo'yish kerak ekan

**Comment by FarrukhMahkamov** [comment]
Hop rahmat.To'grlab qo'ydim
