### ISSUE TITLE
section dagi background color ga max-width berilibdi

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [FarrukhMahkamov/Pizza#4]
![Screenshot_3](https://user-images.githubusercontent.com/77617034/116690560-fc891280-a9d2-11eb-86ce-d8263970c416.png)
mana shu section dagi background color ga max-width berilibdi shekilli. uzoqlashtirganda background-color cho'zilmayapti

**Comment by FarrukhMahkamov** [comment]
Hop rahmat to'grlab qo'ydim
