### ISSUE TITLE
form ga label berilmapti

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [FarrukhMahkamov/Pizza#5]
![Screenshot_5](https://user-images.githubusercontent.com/77617034/116690851-70c3b600-a9d3-11eb-810a-075b430672ef.png)
shu formdagi 2ta inputga 2ta label berib visually hidden qilib qo'yish kerak ekan. pastdagi input type="submit" ni buttonda bersa ham bo'lsa kerak

**Comment by FarrukhMahkamov** [comment]
To'grlab qo'ydim rahmat
